### ISSUE TITLE
[Hottake] Let's combine spark-core and spark-extras

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#1036]
I don't think dealing with the complexity of having spark-extras components with peer deps on specific versions of spark-core is worth the time saved downloading unneeded components. Since the extras payload is pretty small (and should stay relatively small), I think we should just do away with the separation for both the vanilla and angular implementations.

**Comment by yodasw16** [comment]
I think this makes sense as long as we have a way for a team to exclude parts that they don't need. That's possible with the Sass, but is it possible with JS if people are just using our es5 bundle?

Hot(ter?) take:

What if we strip spark-core down to the essential global styles (basically just fundamentals) instead of "the stuff most sites need to be a 'spark site'" and release everything else independently?

**Comment by afebbraro** [comment]
I think having the spark core and spark extras was a way to sort of customize-your-build. I think we can figure out how important we think that is. If its not important then make every just spark and get rid of spark-core and spark-extras. If we think its's really important then I agree with Dave's idea. I will say that from a maintenance perspective, having one package would be a lot easier (just spark).
