### ISSUE TITLE
[BUG?] Lodash's `uniqueID` method is not globally unique and creates duplicate IDs, at least on the modal docs page for react

### ISSUE THREAD

**Issue by 13protons** [sparkdesignsystem/spark-design-system#1149]
This may not be a bug in lodash's method *per-se*, but does mean that we need find an alternate method for generating UIDs for components. 

https://github.com/sparkdesignsystem/spark-design-system/blob/1078-react-modal/src/react/projects/spark-core-react/src/SprkModal/SprkModal.js#L181

<img width="487" alt="screen shot 2019-02-27 at 10 07 02 am" src="https://user-images.githubusercontent.com/1456258/53499976-7af66c80-3a77-11e9-9e99-5b54cfc8d9fa.png">

**Comment by 13protons** [comment]
We should consider pulling in an implementation of CUID, if this ID is a truly important part of the system. 

https://www.npmjs.com/package/cuid#short-urls

**Comment by 13protons** [comment]
A similar issue in SO: 

https://stackoverflow.com/questions/29420835/how-to-generate-unique-ids-for-form-labels-in-react

Also, the pattern for Redux is to wrap the entire component tree in a `<Provider/>` component

https://react-redux.js.org/api/provider

**Comment by bobwise** [comment]
React only requires unique keys for dynamic sibling components that are rendered from an array of children.

Keys used within arrays should be unique among their siblings, but they do not need to be globally unique.

So this is fine, because the repeating keys are not siblings:
```
<div>
  <div key="1">one</div>
  <div key="2">two</div>
</div>
<div>
  <div key="1">won</div>
  <div key="2">too</div>
</div>
```


The issue on the modal docs page is ok, because the modals are not dymanically generated. `lodash` should work fine for us as long as we are generating the ids for all of the dynamic children in the same context (we're not calling out into a separate library or something, for example).
