### ISSUE TITLE
Vulnerability - Upgrade NYC to @latest

### ISSUE THREAD

**Issue by 13protons** [sparkdesignsystem/spark-design-system#1191]
Our version of nyc (coverage reporting) has been flagged with vulnerabilities in it's downstream dependency chain. 

This can be fixed by upgrading to the latest version of nyc, as this will update its dependents to all known good versions: 

https://snyk.io/test/npm/nyc

## The Fix:
Upgrade `nyc` to v13.3.0 (currently 13.0.1)

https://github.com/sparkdesignsystem/spark-design-system/blob/staging/packages/spark-core/package.json#L32

Acceptance:

This is a minor upgrade that should have no effect on our test suite or coverage reporting. 

1. Move `nyc` from `dependencies` to `devDependencies`
2. Run the test and coverage suite before and after the upgrade to confirm this is the case.

**Comment by yodasw16** [comment]
Can't we just move all of these dependencies to be dev dependencies instead? Like, why is Chai, Sinon, nyc, etc. listed as dependencies instead of dev? https://github.com/sparkdesignsystem/spark-design-system/blob/staging/packages/spark-core/package.json#L32

The package.json you linked is for our docs site and has it as a dev dependency, but the actual packages we are releasing don't.

**Comment by yodasw16** [comment]
Also, whatever the solution, we need to patch this in spark-core v9.0.0 as well as v10.0.0

**Comment by 13protons** [comment]
Ah, good catch. Wrong package json, but still probably not a bad idea to upgrade. 13.0.1 > 13.3.0 fixes 4 separate downstream bugs at once and shouldn't impact at our level.

**Comment by yodasw16** [comment]
Moving the dependency to devDependencies and moving the version update to another issue.
