### ISSUE TITLE
Getting started guide: Designer edition

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#122]

**Comment by afebbraro** [comment]
This is something we should integrate on the main Spark documentation page.

**Comment by philrinke** [comment]
initial thoughts on getting started for designers:

The Spark Design System is an ever evolving framework that contains all visual assets used to create a responsive web experience. For a designer, Spark provides visual documentation and recommendations on how to apply the visual styles and how to use the components. 

Every design element housed within Spark has been built out in our Spark Toolkit to help with rapid design and layout prototyping. 

The Spark Design System Team makes frequent updates to the Spark Toolkit to ensure that it is always up to date with our latest design recommendations. Please check in here to make sure you have the latest version.

**Comment by RCopeland** [comment]
I'll write up instructions regarding usage of the sketch file

**Comment by RCopeland** [comment]
**first draft**

## Sketch
To use the Spark Design System Sketch template, follow these steps:

* download the template file.
* open file in sketch, then click File -> Save as Template.
* create a new document, by clicking File -> New From Template -> Spark Design System (version)

When the new document is opened, you'll see a list of Pages.

* Blank Page - this is the default workspace.
* Quick Start - this page contains some quick layouts for getting started quickly. (i.e. A page with a Masthead and Footer Layout in place)
* Symbols - these are the pieces of Spark as defined in Sketch, no need to edit this page.

### Using Spark Components

In order to insert a Spark Component into your design:

* click the Insert button
* hover over Symbols
* select Component to insert
* see available properties in the right pane of selected component.

## Changes

The Spark Sketch template will be updated with each release of Spark. If you want to make changes, do so only in your local copy. If you wish to add a component to Spark officially, see the Contribution process.
