### ISSUE TITLE
Take a look at tertiary button in IE11 React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1337]
**User Story:**
As Spark we want to look at what is going on with the tertiary button in React IE11.

**Notes:**
Requestor: React Code Review 4/22

**AC:**
- Take a look at tertiary button in IE11 React

## @RVMendoza  research found that:
- Something in Spark turns `background-color: transparent` to `background-color: initial` which is something that IE11 ignores.
- Might be a spark polyfill or sass setting

## Ruled Out Possibilities
- Not something create-react-app is doing
- Not something SASS alone is doing
We know this because we used create-react app and it wasn't doing any of this UNTIL spark-core is installed.

**Comment by RVMendoza** [comment]
Please see description for latest findings!

**Comment by RVMendoza** [comment]
Closing this issue. We've concluded it's a drizzle issue.
The main problem is that somehow `background-color: transparent` was being turned into `background-color: initial` in IE11 which it ignores.

Concluded because in IE11:
- Made a create-react app (it was fine)
- everything above + sass (it was fine)
- everything above + normalize and reset from scales (it was fine)
- everything above + spark core (it was fine)
- everything above + spark core vanilla (it was fine)
- everything above + spark react (it was fine)

Final conclusion: This is drizzle's fault, and we're dropping it soon anyways, so we'll leave it alone.
