### ISSUE TITLE
Breakdown remaining work for Angular Stepper

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1564]
**User Story:**
As Spark we want to breakdown the remaining work so that we can prioritize into future sprints. 

**AC:**
-Breakdown remaining work into future Issues.

**Comment by RVMendoza** [comment]
Still needs to be done:
- Animation / timing of sliding action, right now the timing is off (related to setTimeout as well)
- The activated step needs take the same amount of space and not disappear - the space so there's space for slider
- Addressing accessibility - tab navigation etc
- SetTimeout is probably not the best choice to emit offsetTop -- perhaps there's a lifecycle solution
- Content for slider is only being taken by the step emitting `content` which is weird because it should be able to take it from the `let` loop. Need to look into why.
- Write tests for each component
- Documentation and stepper activation in docs

**Comment by RVMendoza** [comment]
@ssabo1 I put this in "review"
