### ISSUE TITLE
[Bug] Fix Border on Angular & Vanilla Inputs

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1678]
**User Story:**
Boarder on inputs currently stays green when they should go back to black.

**Notes:**
- This is for Angular and Vanilla. While upgrading Spark Angular 6 to 7, the following issue came up that are unrelated to upgrade.

**AC:**
- Selected State - Boarder on inputs will stays green when selected.
- Not Selected State - When input is not selected, boarder will be black.

**Comment by yodasw16** [comment]
@afebbraro Can you confirm this is an issue? Or explain the issue to me, if you remember. I tested this in all frameworks and I see a grey border, then green on focus, and back to grey on blur. Same thing if it is empty or has text in it. Did this maybe get fixed with another issue without realizing this issue existed?

**Comment by ssabo1** [comment]
no longer an issue
