### ISSUE TITLE
Clean up Pixel Spacing - Huge Input all packages

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1758]
**User Story:**
As Spark we want to clean up the spacing issue with our Huge Input.

**Notes:**
Currently the user inputted value is shifted to the right by a few px.
![image.png](https://images.zenhubusercontent.com/5c98da1df75c1c000158e457/bfdbc049-e0b1-4614-ba6d-a2f24eea49fc)

**AC:**
- user inputted value will be in line with the label is shifted to the right by a few px.

**Comment by afebbraro** [comment]
Some info on this after researching. The indentation on the placeholder/value was because the label is positioned from the left side of the bounding box and the placeholder/value is positioned from the left side starting at where the border ends. So, say it's positioned 16px over, its actually 18px (16px + 2px border-width) over and the label is only 16px since it's absolutely positioned. I updated the label positioning to take into account the border-width and that fixes this. In regards to Select inputs, this gets a little more fuzzy. The `<option>` in selects have "white space" in front of them in some browsers, (FF, Edge, IE). This white space can be removed with targeting specific browsers and removing the text-indent via a negative text-indent value but it would require us to monitor this issue and those browsers going forward as this is possibly something that could be changed in a future browser update and thus our negative text-indent could cause text to not display at all. Going to bring this up to Brendan today and see if he's content with the 2px indent in selects in ff, edge, IE11 (Chrome doesn't add the white space and neither does Safari, looks good in both!).

**Comment by afebbraro** [comment]
Closing for now, will resync with Brendan on my comment above tomorroww when he's back in office. This is fixed for chrome / safari. Will make new issues based on Brendan convo.
