### ISSUE TITLE
Tertiary buttons for spark-react in IE11 look wrong

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#2095]
## Describe The Bug
Tertiary buttons in spark-react in IE11 dont look right.

## To Reproduce
1. Go to [https://sparkdesignsystem-react.netlify.com](https://sparkdesignsystem-react.netlify.com) in IE11
2. Click on 'button'
3. Scroll down to 'tertiary buttons'

## Screenshots
<img width="185" alt="Capture" src="https://user-images.githubusercontent.com/412903/66147427-d1fb8b80-e5dc-11e9-9673-b4280d73c13c.PNG">

**Comment by yodasw16** [comment]
This is a bug in our React testing app that exists because create react app doesn't support IE11. The CSS optimization process is converting the `transparent` value to `initial` for some reason that I can't understand and IE11 doesn't support it.

I'm going to close this in the spirit of fewer issues since it won't be a thing after we launch storybook.
