### ISSUE TITLE
[Bug] Teaser Card Image is too tall in IE11 - Angular 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2255]
**User Story:**
Bug with teaser cards in angular - Image is too tall in IE11

**Notes:**
Requestor Rob 10/29/19
A lot of this work is done in this branch (see comment below):
https://github.com/RVMendoza/spark-design-system/tree/card-teaser-stack-ang

**AC:**
- Angular, Teaser Card will be the correct height (check hight that is displayed in HTML & React)

**Comment by guern1kn** [comment]
@RCopeland Can you clarify or get a screenshot?

**Comment by guern1kn** [comment]
The image heights are the same in all frameworks for me. These are the netlify storybook sites in Chrome. Am I missing something?
HTML
<img width="445" alt="Screen Shot 2019-10-31 at 8 58 21 AM" src="https://user-images.githubusercontent.com/15703773/67948827-e7a0a880-fbbc-11e9-892e-9c50224763ec.png">
React
<img width="454" alt="Screen Shot 2019-10-31 at 8 58 43 AM" src="https://user-images.githubusercontent.com/15703773/67948873-0010c300-fbbd-11e9-8a13-7256db108c91.png">
Angular
<img width="461" alt="Screen Shot 2019-10-31 at 8 59 05 AM" src="https://user-images.githubusercontent.com/15703773/67948902-0ef77580-fbbd-11e9-9c3e-5d02c505748b.png">

**Comment by RCopeland** [comment]
Sorry I forgot to say, this was for IE11

**Comment by RVMendoza** [comment]
@ssabo1 we should take this out of the sprint because it's more of a change in our package rather than our storybook work.

We brought it in last week because we were ahead.

a majority of the work on this is done and I kicked it into my fork for the future.
https://github.com/RVMendoza/spark-design-system/tree/card-teaser-stack-ang
so we can note that it's there when we need it.

**Comment by ssabo1** [comment]
this is no longer an issue.
