### ISSUE TITLE
Storybook performance issues

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2604]
**User Story:**
As a Documentation User, the storybook instances and the iframes on the main site should load quickly, so that I can see previews quickly.

**AC:**
- Our Storybook performance audits on Lighthouse and WebpageTest are within 25% of the same audits on an empty storybook site.

Current day:

Lighthouse

<img width="1341" alt="Screen Shot 2020-01-15 at 11 52 13 AM" src="https://user-images.githubusercontent.com/412903/72454035-1d056d00-378e-11ea-83c8-fb1e7786642c.png">

WebpageTest

<img width="1016" alt="Screen Shot 2020-01-15 at 11 57 14 AM" src="https://user-images.githubusercontent.com/412903/72454087-34dcf100-378e-11ea-9128-5259f9bef715.png">

**Comment by RCopeland** [comment]
For now I'm attributing the slow load feeling to the bootup time of storybook's iframe.
I'll look for issues open on storybook for progress on making this faster.
We're already lazy loading the slow content as the testing shows.
Since there isn't any work for this to be performed on our end, I'm closing the issue.
