### ISSUE TITLE
Dropdown should replace the shown text with the title rather than the value.

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#3234]
## Describe The Bug
When a choice is selected, the value thats shown in the dropdown is replaced by the value chosen. However, the 'value' is used instead of the user-friendly 'title'.

## To Reproduce
1. Click to open a dropdown
2. Click a choice

## Expected Behavior
I would expect the title of the choice selected would be visible, rather than the 'value'

**AC:**
- double check React.

**Comment by afebbraro** [comment]
This is a breaking change because it changes the Trigger text from using the value on the choice object to the title text. This means that if someone has "Choice Value" set to the value and the "My Favorite Choice" set to the title. That now, the trigger text will show "My Favorite Choice" instead of "Choice Value".

**Comment by afebbraro** [comment]
Fixed and merged into the "breaking" branch.
