### ISSUE TITLE
Button Upgrades - Part 1 (Angular)

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3316]
**Angular Changes**
- The button ts file is in the inputs directory and should be moved out of the inputs directory as its not an input
- Make spinner into a component/directive instead of creating the markup programmatically.
- [NOT DOING - LOOK AT UPDATE] Update the Angular `sprkButton` directive to add the spinner component if `isSpinning` is `true`. This requires rewriting the `setSpinning` method. We also need to add a way to remove the spinner based on the value of `isSpinning`. People have been using the `cancelSpinning` function from HTML Spark. We need to add this to the Angular component so they don't have to use the HTML one.

## UPDATE:
- Leave existing `isSpinning` input on button, but add deprecation notice on dev docs. 
- "engineering required"
- Hiding or showing the spinner is now the responsibility of the implementor
- Removing `isSpinning` from sprk-button on next release after this one
- All existing buttons will continue to work until deletion of `sprk-button`'s `isSpinning` input happens
- Add new accessibility recommendations https://github.com/sparkdesignsystem/spark-design-system/issues/3569#issuecomment-713131375

**Notes:**
React Changes will be done in #3317

**Comment by RVMendoza** [comment]
@afebbraro let's talk about this when you get back

-----

After some research with @RCopeland and @guern1kn we have some options to explore:

**💡My instinct is that we do Option 1.** I think it's the least destructive, and the most compositional. My only concern is making sure the implementor uses the correct spinner variant corresponding to the button. It's very easy to mess up because secondary buttons use primary spinners. If we figured that out, I'd be all in on Option 1.

-----------



## Option 1: Remove spinning functionality from the button altogether, and let the app show/hide spinner or button text via app state. Spinner is a directive.
  - More compositional+flexible, but less helpful
  - Run the risk of dev using the incorrect spinner variant (corresponding names are already confusing). This is removing current functionality. The directive chooses the correct variants automatically, and this change would require the user to pass in the correct variant.
  - Spinner is more usable in other places
  - Not all buttons have spinners so implementors would only use it when necessary, instead of everywhere.
  - Achieving the goal with the least disruption to the user
  - 3 points estimation


## Option 2: Convert Button into component. sprkSpinner is a directive
- I think we converted button into directive recently...this might be going back to what it was originally
- Allows us to code button in the way we do React
- Changing a fundamental component which would cause a huge breaking change for all apps
- Preserves our helpfulness with spinning variants and their corresponding button styles
- 3 points estimation


## Bonus Option 3: Bring cancel code into sprk-button directive
- Would need to get back the button text that was cleared by setSpinning
- Doesn't really improve our code convention, but it does allow people to cancel spinning without using the HTML version




### Both Option 1 and 2 have benefits:
- Allow us to use `cancelSpinning`
- We aren't directly editing HTML in an angular app
- Spinner is separated and usable in other places
- I already created the sprk-spinner directive from working on it last week
