### ISSUE TITLE
Autocomplete Prototyping Round 2

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3611]
Notes:
https://github.com/sparkdesignsystem/spark-design-system/issues/3596

**AC:**
- more developed prototype
- list of different aria properties and WHY

**Comment by bobwise** [comment]
Prototype: https://codepen.io/bobwise/pen/bGeLpzz?editors=1010

# ARIA Props

## On the announce container
- `aria-live="polite"` - Updates will be read by screen reader without interrupting the current audio.

## On the input
- `role="combobox"`
- `aria-autocomplete="list"`
- `aria-controls="list_id"`
- `aria-activedescendant="option_id"` - indicates the item in the list that has visual focus. This combined with `aria-controls` establishes the relationship between input and list for AT.
- `autocomplete="off`, `autocapitalize="off"`, and `spellcheck="false"` - turn off default browser behavior that can conflict with our functionality.
- `aria-expanded="true/false"`

- we don't need to include `aria-haspopup="listbox"` because this is implicit in `role="combobox"`

## On the list items
- `role="option"`
- `aria-selected="true"` - when active
