### ISSUE TITLE
Lists scss lost in conversion from component to base?

### ISSUE THREAD

**Issue by Udofalcon** [sparkdesignsystem/spark-design-system#430]
## Describe The Bug
The current base _lists.scss is missing the unordered, ordered, and bare modifiers as seen in the [demo site](https://sparkdesignsystem.com/patterns/components/lists) and in previous commits. It looks like they were lost in this commit: https://github.com/sparkdesignsystem/spark-design-system/commit/a0c57f461b243a615d556d88036c267ea738ff32
Was this intentional? I'm also not seeing the root .sprk-b-List class anywhere.

**Comment by afebbraro** [comment]
hey @Udofalcon, Thanks for your inquiry! The current implementation of Spark is correct and there is no bug here with the lists. There are three types of lists as stated in the docs site. The class of `sprk-b-List` is the default list style (unordered, ordered).  Further indentation styling of a list can be achieved with adding the modifier of `sprk-b-List--indented`. The bare modifier of `sprk-b-List--bare`  is also still available like the docs mention. You do not see the `sprk-b-List` and the `sprk-b-List--bare` classes in that Spark scss file because it does not need to be there as it's implemented by ScalesCSS which is a dependency of Spark. That commit you listed was correct in that it cleaned up the Spark Lists implementation.

**Comment by afebbraro** [comment]
@Udofalcon , I'm going to close this issue. If you have any other questions please let us know! Thank you!
